shape(car_11,rectangle).
shape(car_12,rectangle).
shape(car_13,rectangle).
shape(car_14,rectangle).
shape(car_21,u_shaped).
shape(car_22,u_shaped).
shape(car_23,rectangle).
shape(car_31,rectangle).
shape(car_32,hexagon).
shape(car_33,rectangle).
shape(car_41,u_shaped).
shape(car_42,rectangle).
shape(car_43,elipse).
shape(car_44,rectangle).
shape(car_51,rectangle).
shape(car_52,rectangle).
shape(car_53,rectangle).
shape(car_61,rectangle).
shape(car_62,rectangle).
shape(car_71,rectangle).
shape(car_72,u_shaped).
shape(car_73,rectangle).
shape(car_81,rectangle).
shape(car_82,u_shaped).
shape(car_91,u_shaped).
shape(car_92,rectangle).
shape(car_93,rectangle).
shape(car_94,u_shaped).
shape(car_101,u_shaped).
shape(car_102,rectangle).
