grandparent(bob,bob,0).
grandparent(bob,dad(bob),0).
grandparent(bob,mum(bob),0).
grandparent(bob,dad(dad(bob)),0).
grandparent(bob,dad(mum(bob)),0).
grandparent(bob,mum(dad(bob)),0).
grandparent(bob,mum(mum(bob)),0).
grandparent(bob,jo,0).
grandparent(bob,dad(jo),0).
grandparent(bob,mum(jo),0).
grandparent(bob,dad(dad(jo)),0).
grandparent(bob,dad(mum(jo)),0).
grandparent(bob,mum(dad(jo)),0).
grandparent(bob,mum(mum(jo)),0).
grandparent(bob,peter,0).
grandparent(bob,dad(peter),0).
grandparent(bob,mum(peter),0).
grandparent(bob,dad(dad(peter)),0).
grandparent(bob,dad(mum(peter)),0).
grandparent(bob,mum(dad(peter)),0).
grandparent(bob,mum(mum(peter)),0).
grandparent(bob,jane,0).
grandparent(bob,dad(jane),0).
grandparent(bob,mum(jane),0).
grandparent(bob,dad(dad(jane)),0).
grandparent(bob,dad(mum(jane)),0).
grandparent(bob,mum(dad(jane)),0).
grandparent(bob,mum(mum(jane)),0).
grandparent(dad(bob),bob,0).
grandparent(dad(bob),dad(bob),0).
grandparent(dad(bob),mum(bob),0).
grandparent(dad(bob),dad(dad(bob)),0).
grandparent(dad(bob),dad(mum(bob)),0).
grandparent(dad(bob),mum(dad(bob)),0).
grandparent(dad(bob),mum(mum(bob)),0).
grandparent(dad(bob),jo,0).
grandparent(dad(bob),dad(jo),0).
grandparent(dad(bob),mum(jo),0).
grandparent(dad(bob),dad(dad(jo)),0).
grandparent(dad(bob),dad(mum(jo)),0).
grandparent(dad(bob),mum(dad(jo)),0).
grandparent(dad(bob),mum(mum(jo)),0).
grandparent(dad(bob),peter,0).
grandparent(dad(bob),dad(peter),0).
grandparent(dad(bob),mum(peter),0).
grandparent(dad(bob),dad(dad(peter)),0).
grandparent(dad(bob),dad(mum(peter)),0).
grandparent(dad(bob),mum(dad(peter)),0).
grandparent(dad(bob),mum(mum(peter)),0).
grandparent(dad(bob),jane,0).
grandparent(dad(bob),dad(jane),0).
grandparent(dad(bob),mum(jane),0).
grandparent(dad(bob),dad(dad(jane)),0).
grandparent(dad(bob),dad(mum(jane)),0).
grandparent(dad(bob),mum(dad(jane)),0).
grandparent(dad(bob),mum(mum(jane)),0).
grandparent(mum(bob),bob,0).
grandparent(mum(bob),dad(bob),0).
grandparent(mum(bob),mum(bob),0).
grandparent(mum(bob),dad(dad(bob)),0).
grandparent(mum(bob),dad(mum(bob)),0).
grandparent(mum(bob),mum(dad(bob)),0).
grandparent(mum(bob),mum(mum(bob)),0).
grandparent(mum(bob),jo,0).
grandparent(mum(bob),dad(jo),0).
grandparent(mum(bob),mum(jo),0).
grandparent(mum(bob),dad(dad(jo)),0).
grandparent(mum(bob),dad(mum(jo)),0).
grandparent(mum(bob),mum(dad(jo)),0).
grandparent(mum(bob),mum(mum(jo)),0).
grandparent(mum(bob),peter,0).
grandparent(mum(bob),dad(peter),0).
grandparent(mum(bob),mum(peter),0).
grandparent(mum(bob),dad(dad(peter)),0).
grandparent(mum(bob),dad(mum(peter)),0).
grandparent(mum(bob),mum(dad(peter)),0).
grandparent(mum(bob),mum(mum(peter)),0).
grandparent(mum(bob),jane,0).
grandparent(mum(bob),dad(jane),0).
grandparent(mum(bob),mum(jane),0).
grandparent(mum(bob),dad(dad(jane)),0).
grandparent(mum(bob),dad(mum(jane)),0).
grandparent(mum(bob),mum(dad(jane)),0).
grandparent(mum(bob),mum(mum(jane)),0).
grandparent(dad(dad(bob)),dad(bob),0).
grandparent(dad(dad(bob)),mum(bob),0).
grandparent(dad(dad(bob)),dad(dad(bob)),0).
grandparent(dad(dad(bob)),dad(mum(bob)),0).
grandparent(dad(dad(bob)),mum(dad(bob)),0).
grandparent(dad(dad(bob)),mum(mum(bob)),0).
grandparent(dad(dad(bob)),jo,0).
grandparent(dad(dad(bob)),dad(jo),0).
grandparent(dad(dad(bob)),mum(jo),0).
grandparent(dad(dad(bob)),dad(dad(jo)),0).
grandparent(dad(dad(bob)),dad(mum(jo)),0).
grandparent(dad(dad(bob)),mum(dad(jo)),0).
grandparent(dad(dad(bob)),mum(mum(jo)),0).
grandparent(dad(dad(bob)),peter,0).
grandparent(dad(dad(bob)),dad(peter),0).
grandparent(dad(dad(bob)),mum(peter),0).
grandparent(dad(dad(bob)),dad(dad(peter)),0).
grandparent(dad(dad(bob)),dad(mum(peter)),0).
grandparent(dad(dad(bob)),mum(dad(peter)),0).
grandparent(dad(dad(bob)),mum(mum(peter)),0).
grandparent(dad(dad(bob)),jane,0).
grandparent(dad(dad(bob)),dad(jane),0).
grandparent(dad(dad(bob)),mum(jane),0).
grandparent(dad(dad(bob)),dad(dad(jane)),0).
grandparent(dad(dad(bob)),dad(mum(jane)),0).
grandparent(dad(dad(bob)),mum(dad(jane)),0).
grandparent(dad(dad(bob)),mum(mum(jane)),0).
grandparent(dad(mum(bob)),dad(bob),0).
grandparent(dad(mum(bob)),mum(bob),0).
grandparent(dad(mum(bob)),dad(dad(bob)),0).
grandparent(dad(mum(bob)),dad(mum(bob)),0).
grandparent(dad(mum(bob)),mum(dad(bob)),0).
grandparent(dad(mum(bob)),mum(mum(bob)),0).
grandparent(dad(mum(bob)),jo,0).
grandparent(dad(mum(bob)),dad(jo),0).
grandparent(dad(mum(bob)),mum(jo),0).
grandparent(dad(mum(bob)),dad(dad(jo)),0).
grandparent(dad(mum(bob)),dad(mum(jo)),0).
grandparent(dad(mum(bob)),mum(dad(jo)),0).
grandparent(dad(mum(bob)),mum(mum(jo)),0).
grandparent(dad(mum(bob)),peter,0).
grandparent(dad(mum(bob)),dad(peter),0).
grandparent(dad(mum(bob)),mum(peter),0).
grandparent(dad(mum(bob)),dad(dad(peter)),0).
grandparent(dad(mum(bob)),dad(mum(peter)),0).
grandparent(dad(mum(bob)),mum(dad(peter)),0).
grandparent(dad(mum(bob)),mum(mum(peter)),0).
grandparent(dad(mum(bob)),jane,0).
grandparent(dad(mum(bob)),dad(jane),0).
grandparent(dad(mum(bob)),mum(jane),0).
grandparent(dad(mum(bob)),dad(dad(jane)),0).
grandparent(dad(mum(bob)),dad(mum(jane)),0).
grandparent(dad(mum(bob)),mum(dad(jane)),0).
grandparent(dad(mum(bob)),mum(mum(jane)),0).
grandparent(mum(dad(bob)),dad(bob),0).
grandparent(mum(dad(bob)),mum(bob),0).
grandparent(mum(dad(bob)),dad(dad(bob)),0).
grandparent(mum(dad(bob)),dad(mum(bob)),0).
grandparent(mum(dad(bob)),mum(dad(bob)),0).
grandparent(mum(dad(bob)),mum(mum(bob)),0).
grandparent(mum(dad(bob)),jo,0).
grandparent(mum(dad(bob)),dad(jo),0).
grandparent(mum(dad(bob)),mum(jo),0).
grandparent(mum(dad(bob)),dad(dad(jo)),0).
grandparent(mum(dad(bob)),dad(mum(jo)),0).
grandparent(mum(dad(bob)),mum(dad(jo)),0).
grandparent(mum(dad(bob)),mum(mum(jo)),0).
grandparent(mum(dad(bob)),peter,0).
grandparent(mum(dad(bob)),dad(peter),0).
grandparent(mum(dad(bob)),mum(peter),0).
grandparent(mum(dad(bob)),dad(dad(peter)),0).
grandparent(mum(dad(bob)),dad(mum(peter)),0).
grandparent(mum(dad(bob)),mum(dad(peter)),0).
grandparent(mum(dad(bob)),mum(mum(peter)),0).
grandparent(mum(dad(bob)),jane,0).
grandparent(mum(dad(bob)),dad(jane),0).
grandparent(mum(dad(bob)),mum(jane),0).
grandparent(mum(dad(bob)),dad(dad(jane)),0).
grandparent(mum(dad(bob)),dad(mum(jane)),0).
grandparent(mum(dad(bob)),mum(dad(jane)),0).
grandparent(mum(dad(bob)),mum(mum(jane)),0).
grandparent(mum(mum(bob)),dad(bob),0).
grandparent(mum(mum(bob)),mum(bob),0).
grandparent(mum(mum(bob)),dad(dad(bob)),0).
grandparent(mum(mum(bob)),dad(mum(bob)),0).
grandparent(mum(mum(bob)),mum(dad(bob)),0).
grandparent(mum(mum(bob)),mum(mum(bob)),0).
grandparent(mum(mum(bob)),jo,0).
grandparent(mum(mum(bob)),dad(jo),0).
grandparent(mum(mum(bob)),mum(jo),0).
grandparent(mum(mum(bob)),dad(dad(jo)),0).
grandparent(mum(mum(bob)),dad(mum(jo)),0).
grandparent(mum(mum(bob)),mum(dad(jo)),0).
grandparent(mum(mum(bob)),mum(mum(jo)),0).
grandparent(mum(mum(bob)),peter,0).
grandparent(mum(mum(bob)),dad(peter),0).
grandparent(mum(mum(bob)),mum(peter),0).
grandparent(mum(mum(bob)),dad(dad(peter)),0).
grandparent(mum(mum(bob)),dad(mum(peter)),0).
grandparent(mum(mum(bob)),mum(dad(peter)),0).
grandparent(mum(mum(bob)),mum(mum(peter)),0).
grandparent(mum(mum(bob)),jane,0).
grandparent(mum(mum(bob)),dad(jane),0).
grandparent(mum(mum(bob)),mum(jane),0).
grandparent(mum(mum(bob)),dad(dad(jane)),0).
grandparent(mum(mum(bob)),dad(mum(jane)),0).
grandparent(mum(mum(bob)),mum(dad(jane)),0).
grandparent(mum(mum(bob)),mum(mum(jane)),0).
grandparent(jo,bob,0).
grandparent(jo,dad(bob),0).
grandparent(jo,mum(bob),0).
grandparent(jo,dad(dad(bob)),0).
grandparent(jo,dad(mum(bob)),0).
grandparent(jo,mum(dad(bob)),0).
grandparent(jo,mum(mum(bob)),0).
grandparent(jo,jo,0).
grandparent(jo,dad(jo),0).
grandparent(jo,mum(jo),0).
grandparent(jo,dad(dad(jo)),0).
grandparent(jo,dad(mum(jo)),0).
grandparent(jo,mum(dad(jo)),0).
grandparent(jo,mum(mum(jo)),0).
grandparent(jo,peter,0).
grandparent(jo,dad(peter),0).
grandparent(jo,mum(peter),0).
grandparent(jo,dad(dad(peter)),0).
grandparent(jo,dad(mum(peter)),0).
grandparent(jo,mum(dad(peter)),0).
grandparent(jo,mum(mum(peter)),0).
grandparent(jo,jane,0).
grandparent(jo,dad(jane),0).
grandparent(jo,mum(jane),0).
grandparent(jo,dad(dad(jane)),0).
grandparent(jo,dad(mum(jane)),0).
grandparent(jo,mum(dad(jane)),0).
grandparent(jo,mum(mum(jane)),0).
grandparent(dad(jo),bob,0).
grandparent(dad(jo),dad(bob),0).
grandparent(dad(jo),mum(bob),0).
grandparent(dad(jo),dad(dad(bob)),0).
grandparent(dad(jo),dad(mum(bob)),0).
grandparent(dad(jo),mum(dad(bob)),0).
grandparent(dad(jo),mum(mum(bob)),0).
grandparent(dad(jo),jo,0).
grandparent(dad(jo),dad(jo),0).
grandparent(dad(jo),mum(jo),0).
grandparent(dad(jo),dad(dad(jo)),0).
grandparent(dad(jo),dad(mum(jo)),0).
grandparent(dad(jo),mum(dad(jo)),0).
grandparent(dad(jo),mum(mum(jo)),0).
grandparent(dad(jo),peter,0).
grandparent(dad(jo),dad(peter),0).
grandparent(dad(jo),mum(peter),0).
grandparent(dad(jo),dad(dad(peter)),0).
grandparent(dad(jo),dad(mum(peter)),0).
grandparent(dad(jo),mum(dad(peter)),0).
grandparent(dad(jo),mum(mum(peter)),0).
grandparent(dad(jo),jane,0).
grandparent(dad(jo),dad(jane),0).
grandparent(dad(jo),mum(jane),0).
grandparent(dad(jo),dad(dad(jane)),0).
grandparent(dad(jo),dad(mum(jane)),0).
grandparent(dad(jo),mum(dad(jane)),0).
grandparent(dad(jo),mum(mum(jane)),0).
grandparent(mum(jo),bob,0).
grandparent(mum(jo),dad(bob),0).
grandparent(mum(jo),mum(bob),0).
grandparent(mum(jo),dad(dad(bob)),0).
grandparent(mum(jo),dad(mum(bob)),0).
grandparent(mum(jo),mum(dad(bob)),0).
grandparent(mum(jo),mum(mum(bob)),0).
grandparent(mum(jo),jo,0).
grandparent(mum(jo),dad(jo),0).
grandparent(mum(jo),mum(jo),0).
grandparent(mum(jo),dad(dad(jo)),0).
grandparent(mum(jo),dad(mum(jo)),0).
grandparent(mum(jo),mum(dad(jo)),0).
grandparent(mum(jo),mum(mum(jo)),0).
grandparent(mum(jo),peter,0).
grandparent(mum(jo),dad(peter),0).
grandparent(mum(jo),mum(peter),0).
grandparent(mum(jo),dad(dad(peter)),0).
grandparent(mum(jo),dad(mum(peter)),0).
grandparent(mum(jo),mum(dad(peter)),0).
grandparent(mum(jo),mum(mum(peter)),0).
grandparent(mum(jo),jane,0).
grandparent(mum(jo),dad(jane),0).
grandparent(mum(jo),mum(jane),0).
grandparent(mum(jo),dad(dad(jane)),0).
grandparent(mum(jo),dad(mum(jane)),0).
grandparent(mum(jo),mum(dad(jane)),0).
grandparent(mum(jo),mum(mum(jane)),0).
grandparent(dad(dad(jo)),bob,0).
grandparent(dad(dad(jo)),dad(bob),0).
grandparent(dad(dad(jo)),mum(bob),0).
grandparent(dad(dad(jo)),dad(dad(bob)),0).
grandparent(dad(dad(jo)),dad(mum(bob)),0).
grandparent(dad(dad(jo)),mum(dad(bob)),0).
grandparent(dad(dad(jo)),mum(mum(bob)),0).
grandparent(dad(dad(jo)),dad(jo),0).
grandparent(dad(dad(jo)),mum(jo),0).
grandparent(dad(dad(jo)),dad(dad(jo)),0).
grandparent(dad(dad(jo)),dad(mum(jo)),0).
grandparent(dad(dad(jo)),mum(dad(jo)),0).
grandparent(dad(dad(jo)),mum(mum(jo)),0).
grandparent(dad(dad(jo)),peter,0).
grandparent(dad(dad(jo)),dad(peter),0).
grandparent(dad(dad(jo)),mum(peter),0).
grandparent(dad(dad(jo)),dad(dad(peter)),0).
grandparent(dad(dad(jo)),dad(mum(peter)),0).
grandparent(dad(dad(jo)),mum(dad(peter)),0).
grandparent(dad(dad(jo)),mum(mum(peter)),0).
grandparent(dad(dad(jo)),jane,0).
grandparent(dad(dad(jo)),dad(jane),0).
grandparent(dad(dad(jo)),mum(jane),0).
grandparent(dad(dad(jo)),dad(dad(jane)),0).
grandparent(dad(dad(jo)),dad(mum(jane)),0).
grandparent(dad(dad(jo)),mum(dad(jane)),0).
grandparent(dad(dad(jo)),mum(mum(jane)),0).
grandparent(dad(mum(jo)),bob,0).
grandparent(dad(mum(jo)),dad(bob),0).
grandparent(dad(mum(jo)),mum(bob),0).
grandparent(dad(mum(jo)),dad(dad(bob)),0).
grandparent(dad(mum(jo)),dad(mum(bob)),0).
grandparent(dad(mum(jo)),mum(dad(bob)),0).
grandparent(dad(mum(jo)),mum(mum(bob)),0).
grandparent(dad(mum(jo)),dad(jo),0).
grandparent(dad(mum(jo)),mum(jo),0).
grandparent(dad(mum(jo)),dad(dad(jo)),0).
grandparent(dad(mum(jo)),dad(mum(jo)),0).
grandparent(dad(mum(jo)),mum(dad(jo)),0).
grandparent(dad(mum(jo)),mum(mum(jo)),0).
grandparent(dad(mum(jo)),peter,0).
grandparent(dad(mum(jo)),dad(peter),0).
grandparent(dad(mum(jo)),mum(peter),0).
grandparent(dad(mum(jo)),dad(dad(peter)),0).
grandparent(dad(mum(jo)),dad(mum(peter)),0).
grandparent(dad(mum(jo)),mum(dad(peter)),0).
grandparent(dad(mum(jo)),mum(mum(peter)),0).
grandparent(dad(mum(jo)),jane,0).
grandparent(dad(mum(jo)),dad(jane),0).
grandparent(dad(mum(jo)),mum(jane),0).
grandparent(dad(mum(jo)),dad(dad(jane)),0).
grandparent(dad(mum(jo)),dad(mum(jane)),0).
grandparent(dad(mum(jo)),mum(dad(jane)),0).
grandparent(dad(mum(jo)),mum(mum(jane)),0).
grandparent(mum(dad(jo)),bob,0).
grandparent(mum(dad(jo)),dad(bob),0).
grandparent(mum(dad(jo)),mum(bob),0).
grandparent(mum(dad(jo)),dad(dad(bob)),0).
grandparent(mum(dad(jo)),dad(mum(bob)),0).
grandparent(mum(dad(jo)),mum(dad(bob)),0).
grandparent(mum(dad(jo)),mum(mum(bob)),0).
grandparent(mum(dad(jo)),dad(jo),0).
grandparent(mum(dad(jo)),mum(jo),0).
grandparent(mum(dad(jo)),dad(dad(jo)),0).
grandparent(mum(dad(jo)),dad(mum(jo)),0).
grandparent(mum(dad(jo)),mum(dad(jo)),0).
grandparent(mum(dad(jo)),mum(mum(jo)),0).
grandparent(mum(dad(jo)),peter,0).
grandparent(mum(dad(jo)),dad(peter),0).
grandparent(mum(dad(jo)),mum(peter),0).
grandparent(mum(dad(jo)),dad(dad(peter)),0).
grandparent(mum(dad(jo)),dad(mum(peter)),0).
grandparent(mum(dad(jo)),mum(dad(peter)),0).
grandparent(mum(dad(jo)),mum(mum(peter)),0).
grandparent(mum(dad(jo)),jane,0).
grandparent(mum(dad(jo)),dad(jane),0).
grandparent(mum(dad(jo)),mum(jane),0).
grandparent(mum(dad(jo)),dad(dad(jane)),0).
grandparent(mum(dad(jo)),dad(mum(jane)),0).
grandparent(mum(dad(jo)),mum(dad(jane)),0).
grandparent(mum(dad(jo)),mum(mum(jane)),0).
grandparent(mum(mum(jo)),bob,0).
grandparent(mum(mum(jo)),dad(bob),0).
grandparent(mum(mum(jo)),mum(bob),0).
grandparent(mum(mum(jo)),dad(dad(bob)),0).
grandparent(mum(mum(jo)),dad(mum(bob)),0).
grandparent(mum(mum(jo)),mum(dad(bob)),0).
grandparent(mum(mum(jo)),mum(mum(bob)),0).
grandparent(mum(mum(jo)),dad(jo),0).
grandparent(mum(mum(jo)),mum(jo),0).
grandparent(mum(mum(jo)),dad(dad(jo)),0).
grandparent(mum(mum(jo)),dad(mum(jo)),0).
grandparent(mum(mum(jo)),mum(dad(jo)),0).
grandparent(mum(mum(jo)),mum(mum(jo)),0).
grandparent(mum(mum(jo)),peter,0).
grandparent(mum(mum(jo)),dad(peter),0).
grandparent(mum(mum(jo)),mum(peter),0).
grandparent(mum(mum(jo)),dad(dad(peter)),0).
grandparent(mum(mum(jo)),dad(mum(peter)),0).
grandparent(mum(mum(jo)),mum(dad(peter)),0).
grandparent(mum(mum(jo)),mum(mum(peter)),0).
grandparent(mum(mum(jo)),jane,0).
grandparent(mum(mum(jo)),dad(jane),0).
grandparent(mum(mum(jo)),mum(jane),0).
grandparent(mum(mum(jo)),dad(dad(jane)),0).
grandparent(mum(mum(jo)),dad(mum(jane)),0).
grandparent(mum(mum(jo)),mum(dad(jane)),0).
grandparent(mum(mum(jo)),mum(mum(jane)),0).
grandparent(peter,bob,0).
grandparent(peter,dad(bob),0).
grandparent(peter,mum(bob),0).
grandparent(peter,dad(dad(bob)),0).
grandparent(peter,dad(mum(bob)),0).
grandparent(peter,mum(dad(bob)),0).
grandparent(peter,mum(mum(bob)),0).
grandparent(peter,jo,0).
grandparent(peter,dad(jo),0).
grandparent(peter,mum(jo),0).
grandparent(peter,dad(dad(jo)),0).
grandparent(peter,dad(mum(jo)),0).
grandparent(peter,mum(dad(jo)),0).
grandparent(peter,mum(mum(jo)),0).
grandparent(peter,peter,0).
grandparent(peter,dad(peter),0).
grandparent(peter,mum(peter),0).
grandparent(peter,dad(dad(peter)),0).
grandparent(peter,dad(mum(peter)),0).
grandparent(peter,mum(dad(peter)),0).
grandparent(peter,mum(mum(peter)),0).
grandparent(peter,jane,0).
grandparent(peter,dad(jane),0).
grandparent(peter,mum(jane),0).
grandparent(peter,dad(dad(jane)),0).
grandparent(peter,dad(mum(jane)),0).
grandparent(peter,mum(dad(jane)),0).
grandparent(peter,mum(mum(jane)),0).
grandparent(dad(peter),bob,0).
grandparent(dad(peter),dad(bob),0).
grandparent(dad(peter),mum(bob),0).
grandparent(dad(peter),dad(dad(bob)),0).
grandparent(dad(peter),dad(mum(bob)),0).
grandparent(dad(peter),mum(dad(bob)),0).
grandparent(dad(peter),mum(mum(bob)),0).
grandparent(dad(peter),jo,0).
grandparent(dad(peter),dad(jo),0).
grandparent(dad(peter),mum(jo),0).
grandparent(dad(peter),dad(dad(jo)),0).
grandparent(dad(peter),dad(mum(jo)),0).
grandparent(dad(peter),mum(dad(jo)),0).
grandparent(dad(peter),mum(mum(jo)),0).
grandparent(dad(peter),peter,0).
grandparent(dad(peter),dad(peter),0).
grandparent(dad(peter),mum(peter),0).
grandparent(dad(peter),dad(dad(peter)),0).
grandparent(dad(peter),dad(mum(peter)),0).
grandparent(dad(peter),mum(dad(peter)),0).
grandparent(dad(peter),mum(mum(peter)),0).
grandparent(dad(peter),jane,0).
grandparent(dad(peter),dad(jane),0).
grandparent(dad(peter),mum(jane),0).
grandparent(dad(peter),dad(dad(jane)),0).
grandparent(dad(peter),dad(mum(jane)),0).
grandparent(dad(peter),mum(dad(jane)),0).
grandparent(dad(peter),mum(mum(jane)),0).
grandparent(mum(peter),bob,0).
grandparent(mum(peter),dad(bob),0).
grandparent(mum(peter),mum(bob),0).
grandparent(mum(peter),dad(dad(bob)),0).
grandparent(mum(peter),dad(mum(bob)),0).
grandparent(mum(peter),mum(dad(bob)),0).
grandparent(mum(peter),mum(mum(bob)),0).
grandparent(mum(peter),jo,0).
grandparent(mum(peter),dad(jo),0).
grandparent(mum(peter),mum(jo),0).
grandparent(mum(peter),dad(dad(jo)),0).
grandparent(mum(peter),dad(mum(jo)),0).
grandparent(mum(peter),mum(dad(jo)),0).
grandparent(mum(peter),mum(mum(jo)),0).
grandparent(mum(peter),peter,0).
grandparent(mum(peter),dad(peter),0).
grandparent(mum(peter),mum(peter),0).
grandparent(mum(peter),dad(dad(peter)),0).
grandparent(mum(peter),dad(mum(peter)),0).
grandparent(mum(peter),mum(dad(peter)),0).
grandparent(mum(peter),mum(mum(peter)),0).
grandparent(mum(peter),jane,0).
grandparent(mum(peter),dad(jane),0).
grandparent(mum(peter),mum(jane),0).
grandparent(mum(peter),dad(dad(jane)),0).
grandparent(mum(peter),dad(mum(jane)),0).
grandparent(mum(peter),mum(dad(jane)),0).
grandparent(mum(peter),mum(mum(jane)),0).
grandparent(dad(dad(peter)),bob,0).
grandparent(dad(dad(peter)),dad(bob),0).
grandparent(dad(dad(peter)),mum(bob),0).
grandparent(dad(dad(peter)),dad(dad(bob)),0).
grandparent(dad(dad(peter)),dad(mum(bob)),0).
grandparent(dad(dad(peter)),mum(dad(bob)),0).
grandparent(dad(dad(peter)),mum(mum(bob)),0).
grandparent(dad(dad(peter)),jo,0).
grandparent(dad(dad(peter)),dad(jo),0).
grandparent(dad(dad(peter)),mum(jo),0).
grandparent(dad(dad(peter)),dad(dad(jo)),0).
grandparent(dad(dad(peter)),dad(mum(jo)),0).
grandparent(dad(dad(peter)),mum(dad(jo)),0).
grandparent(dad(dad(peter)),mum(mum(jo)),0).
grandparent(dad(dad(peter)),dad(peter),0).
grandparent(dad(dad(peter)),mum(peter),0).
grandparent(dad(dad(peter)),dad(dad(peter)),0).
grandparent(dad(dad(peter)),dad(mum(peter)),0).
grandparent(dad(dad(peter)),mum(dad(peter)),0).
grandparent(dad(dad(peter)),mum(mum(peter)),0).
grandparent(dad(dad(peter)),jane,0).
grandparent(dad(dad(peter)),dad(jane),0).
grandparent(dad(dad(peter)),mum(jane),0).
grandparent(dad(dad(peter)),dad(dad(jane)),0).
grandparent(dad(dad(peter)),dad(mum(jane)),0).
grandparent(dad(dad(peter)),mum(dad(jane)),0).
grandparent(dad(dad(peter)),mum(mum(jane)),0).
grandparent(dad(mum(peter)),bob,0).
grandparent(dad(mum(peter)),dad(bob),0).
grandparent(dad(mum(peter)),mum(bob),0).
grandparent(dad(mum(peter)),dad(dad(bob)),0).
grandparent(dad(mum(peter)),dad(mum(bob)),0).
grandparent(dad(mum(peter)),mum(dad(bob)),0).
grandparent(dad(mum(peter)),mum(mum(bob)),0).
grandparent(dad(mum(peter)),jo,0).
grandparent(dad(mum(peter)),dad(jo),0).
grandparent(dad(mum(peter)),mum(jo),0).
grandparent(dad(mum(peter)),dad(dad(jo)),0).
grandparent(dad(mum(peter)),dad(mum(jo)),0).
grandparent(dad(mum(peter)),mum(dad(jo)),0).
grandparent(dad(mum(peter)),mum(mum(jo)),0).
grandparent(dad(mum(peter)),dad(peter),0).
grandparent(dad(mum(peter)),mum(peter),0).
grandparent(dad(mum(peter)),dad(dad(peter)),0).
grandparent(dad(mum(peter)),dad(mum(peter)),0).
grandparent(dad(mum(peter)),mum(dad(peter)),0).
grandparent(dad(mum(peter)),mum(mum(peter)),0).
grandparent(dad(mum(peter)),jane,0).
grandparent(dad(mum(peter)),dad(jane),0).
grandparent(dad(mum(peter)),mum(jane),0).
grandparent(dad(mum(peter)),dad(dad(jane)),0).
grandparent(dad(mum(peter)),dad(mum(jane)),0).
grandparent(dad(mum(peter)),mum(dad(jane)),0).
grandparent(dad(mum(peter)),mum(mum(jane)),0).
grandparent(mum(dad(peter)),bob,0).
grandparent(mum(dad(peter)),dad(bob),0).
grandparent(mum(dad(peter)),mum(bob),0).
grandparent(mum(dad(peter)),dad(dad(bob)),0).
grandparent(mum(dad(peter)),dad(mum(bob)),0).
grandparent(mum(dad(peter)),mum(dad(bob)),0).
grandparent(mum(dad(peter)),mum(mum(bob)),0).
grandparent(mum(dad(peter)),jo,0).
grandparent(mum(dad(peter)),dad(jo),0).
grandparent(mum(dad(peter)),mum(jo),0).
grandparent(mum(dad(peter)),dad(dad(jo)),0).
grandparent(mum(dad(peter)),dad(mum(jo)),0).
grandparent(mum(dad(peter)),mum(dad(jo)),0).
grandparent(mum(dad(peter)),mum(mum(jo)),0).
grandparent(mum(dad(peter)),dad(peter),0).
grandparent(mum(dad(peter)),mum(peter),0).
grandparent(mum(dad(peter)),dad(dad(peter)),0).
grandparent(mum(dad(peter)),dad(mum(peter)),0).
grandparent(mum(dad(peter)),mum(dad(peter)),0).
grandparent(mum(dad(peter)),mum(mum(peter)),0).
grandparent(mum(dad(peter)),jane,0).
grandparent(mum(dad(peter)),dad(jane),0).
grandparent(mum(dad(peter)),mum(jane),0).
grandparent(mum(dad(peter)),dad(dad(jane)),0).
grandparent(mum(dad(peter)),dad(mum(jane)),0).
grandparent(mum(dad(peter)),mum(dad(jane)),0).
grandparent(mum(dad(peter)),mum(mum(jane)),0).
grandparent(mum(mum(peter)),bob,0).
grandparent(mum(mum(peter)),dad(bob),0).
grandparent(mum(mum(peter)),mum(bob),0).
grandparent(mum(mum(peter)),dad(dad(bob)),0).
grandparent(mum(mum(peter)),dad(mum(bob)),0).
grandparent(mum(mum(peter)),mum(dad(bob)),0).
grandparent(mum(mum(peter)),mum(mum(bob)),0).
grandparent(mum(mum(peter)),jo,0).
grandparent(mum(mum(peter)),dad(jo),0).
grandparent(mum(mum(peter)),mum(jo),0).
grandparent(mum(mum(peter)),dad(dad(jo)),0).
grandparent(mum(mum(peter)),dad(mum(jo)),0).
grandparent(mum(mum(peter)),mum(dad(jo)),0).
grandparent(mum(mum(peter)),mum(mum(jo)),0).
grandparent(mum(mum(peter)),dad(peter),0).
grandparent(mum(mum(peter)),mum(peter),0).
grandparent(mum(mum(peter)),dad(dad(peter)),0).
grandparent(mum(mum(peter)),dad(mum(peter)),0).
grandparent(mum(mum(peter)),mum(dad(peter)),0).
grandparent(mum(mum(peter)),mum(mum(peter)),0).
grandparent(mum(mum(peter)),jane,0).
grandparent(mum(mum(peter)),dad(jane),0).
grandparent(mum(mum(peter)),mum(jane),0).
grandparent(mum(mum(peter)),dad(dad(jane)),0).
grandparent(mum(mum(peter)),dad(mum(jane)),0).
grandparent(mum(mum(peter)),mum(dad(jane)),0).
grandparent(mum(mum(peter)),mum(mum(jane)),0).
grandparent(jane,bob,0).
grandparent(jane,dad(bob),0).
grandparent(jane,mum(bob),0).
grandparent(jane,dad(dad(bob)),0).
grandparent(jane,dad(mum(bob)),0).
grandparent(jane,mum(dad(bob)),0).
grandparent(jane,mum(mum(bob)),0).
grandparent(jane,jo,0).
grandparent(jane,dad(jo),0).
grandparent(jane,mum(jo),0).
grandparent(jane,dad(dad(jo)),0).
grandparent(jane,dad(mum(jo)),0).
grandparent(jane,mum(dad(jo)),0).
grandparent(jane,mum(mum(jo)),0).
grandparent(jane,peter,0).
grandparent(jane,dad(peter),0).
grandparent(jane,mum(peter),0).
grandparent(jane,dad(dad(peter)),0).
grandparent(jane,dad(mum(peter)),0).
grandparent(jane,mum(dad(peter)),0).
grandparent(jane,mum(mum(peter)),0).
grandparent(jane,jane,0).
grandparent(jane,dad(jane),0).
grandparent(jane,mum(jane),0).
grandparent(jane,dad(dad(jane)),0).
grandparent(jane,dad(mum(jane)),0).
grandparent(jane,mum(dad(jane)),0).
grandparent(jane,mum(mum(jane)),0).
grandparent(dad(jane),bob,0).
grandparent(dad(jane),dad(bob),0).
grandparent(dad(jane),mum(bob),0).
grandparent(dad(jane),dad(dad(bob)),0).
grandparent(dad(jane),dad(mum(bob)),0).
grandparent(dad(jane),mum(dad(bob)),0).
grandparent(dad(jane),mum(mum(bob)),0).
grandparent(dad(jane),jo,0).
grandparent(dad(jane),dad(jo),0).
grandparent(dad(jane),mum(jo),0).
grandparent(dad(jane),dad(dad(jo)),0).
grandparent(dad(jane),dad(mum(jo)),0).
grandparent(dad(jane),mum(dad(jo)),0).
grandparent(dad(jane),mum(mum(jo)),0).
grandparent(dad(jane),peter,0).
grandparent(dad(jane),dad(peter),0).
grandparent(dad(jane),mum(peter),0).
grandparent(dad(jane),dad(dad(peter)),0).
grandparent(dad(jane),dad(mum(peter)),0).
grandparent(dad(jane),mum(dad(peter)),0).
grandparent(dad(jane),mum(mum(peter)),0).
grandparent(dad(jane),jane,0).
grandparent(dad(jane),dad(jane),0).
grandparent(dad(jane),mum(jane),0).
grandparent(dad(jane),dad(dad(jane)),0).
grandparent(dad(jane),dad(mum(jane)),0).
grandparent(dad(jane),mum(dad(jane)),0).
grandparent(dad(jane),mum(mum(jane)),0).
grandparent(mum(jane),bob,0).
grandparent(mum(jane),dad(bob),0).
grandparent(mum(jane),mum(bob),0).
grandparent(mum(jane),dad(dad(bob)),0).
grandparent(mum(jane),dad(mum(bob)),0).
grandparent(mum(jane),mum(dad(bob)),0).
grandparent(mum(jane),mum(mum(bob)),0).
grandparent(mum(jane),jo,0).
grandparent(mum(jane),dad(jo),0).
grandparent(mum(jane),mum(jo),0).
grandparent(mum(jane),dad(dad(jo)),0).
grandparent(mum(jane),dad(mum(jo)),0).
grandparent(mum(jane),mum(dad(jo)),0).
grandparent(mum(jane),mum(mum(jo)),0).
grandparent(mum(jane),peter,0).
grandparent(mum(jane),dad(peter),0).
grandparent(mum(jane),mum(peter),0).
grandparent(mum(jane),dad(dad(peter)),0).
grandparent(mum(jane),dad(mum(peter)),0).
grandparent(mum(jane),mum(dad(peter)),0).
grandparent(mum(jane),mum(mum(peter)),0).
grandparent(mum(jane),jane,0).
grandparent(mum(jane),dad(jane),0).
grandparent(mum(jane),mum(jane),0).
grandparent(mum(jane),dad(dad(jane)),0).
grandparent(mum(jane),dad(mum(jane)),0).
grandparent(mum(jane),mum(dad(jane)),0).
grandparent(mum(jane),mum(mum(jane)),0).
grandparent(dad(dad(jane)),bob,0).
grandparent(dad(dad(jane)),dad(bob),0).
grandparent(dad(dad(jane)),mum(bob),0).
grandparent(dad(dad(jane)),dad(dad(bob)),0).
grandparent(dad(dad(jane)),dad(mum(bob)),0).
grandparent(dad(dad(jane)),mum(dad(bob)),0).
grandparent(dad(dad(jane)),mum(mum(bob)),0).
grandparent(dad(dad(jane)),jo,0).
grandparent(dad(dad(jane)),dad(jo),0).
grandparent(dad(dad(jane)),mum(jo),0).
grandparent(dad(dad(jane)),dad(dad(jo)),0).
grandparent(dad(dad(jane)),dad(mum(jo)),0).
grandparent(dad(dad(jane)),mum(dad(jo)),0).
grandparent(dad(dad(jane)),mum(mum(jo)),0).
grandparent(dad(dad(jane)),peter,0).
grandparent(dad(dad(jane)),dad(peter),0).
grandparent(dad(dad(jane)),mum(peter),0).
grandparent(dad(dad(jane)),dad(dad(peter)),0).
grandparent(dad(dad(jane)),dad(mum(peter)),0).
grandparent(dad(dad(jane)),mum(dad(peter)),0).
grandparent(dad(dad(jane)),mum(mum(peter)),0).
grandparent(dad(dad(jane)),dad(jane),0).
grandparent(dad(dad(jane)),mum(jane),0).
grandparent(dad(dad(jane)),dad(dad(jane)),0).
grandparent(dad(dad(jane)),dad(mum(jane)),0).
grandparent(dad(dad(jane)),mum(dad(jane)),0).
grandparent(dad(dad(jane)),mum(mum(jane)),0).
grandparent(dad(mum(jane)),bob,0).
grandparent(dad(mum(jane)),dad(bob),0).
grandparent(dad(mum(jane)),mum(bob),0).
grandparent(dad(mum(jane)),dad(dad(bob)),0).
grandparent(dad(mum(jane)),dad(mum(bob)),0).
grandparent(dad(mum(jane)),mum(dad(bob)),0).
grandparent(dad(mum(jane)),mum(mum(bob)),0).
grandparent(dad(mum(jane)),jo,0).
grandparent(dad(mum(jane)),dad(jo),0).
grandparent(dad(mum(jane)),mum(jo),0).
grandparent(dad(mum(jane)),dad(dad(jo)),0).
grandparent(dad(mum(jane)),dad(mum(jo)),0).
grandparent(dad(mum(jane)),mum(dad(jo)),0).
grandparent(dad(mum(jane)),mum(mum(jo)),0).
grandparent(dad(mum(jane)),peter,0).
grandparent(dad(mum(jane)),dad(peter),0).
grandparent(dad(mum(jane)),mum(peter),0).
grandparent(dad(mum(jane)),dad(dad(peter)),0).
grandparent(dad(mum(jane)),dad(mum(peter)),0).
grandparent(dad(mum(jane)),mum(dad(peter)),0).
grandparent(dad(mum(jane)),mum(mum(peter)),0).
grandparent(dad(mum(jane)),dad(jane),0).
grandparent(dad(mum(jane)),mum(jane),0).
grandparent(dad(mum(jane)),dad(dad(jane)),0).
grandparent(dad(mum(jane)),dad(mum(jane)),0).
grandparent(dad(mum(jane)),mum(dad(jane)),0).
grandparent(dad(mum(jane)),mum(mum(jane)),0).
grandparent(mum(dad(jane)),bob,0).
grandparent(mum(dad(jane)),dad(bob),0).
grandparent(mum(dad(jane)),mum(bob),0).
grandparent(mum(dad(jane)),dad(dad(bob)),0).
grandparent(mum(dad(jane)),dad(mum(bob)),0).
grandparent(mum(dad(jane)),mum(dad(bob)),0).
grandparent(mum(dad(jane)),mum(mum(bob)),0).
grandparent(mum(dad(jane)),jo,0).
grandparent(mum(dad(jane)),dad(jo),0).
grandparent(mum(dad(jane)),mum(jo),0).
grandparent(mum(dad(jane)),dad(dad(jo)),0).
grandparent(mum(dad(jane)),dad(mum(jo)),0).
grandparent(mum(dad(jane)),mum(dad(jo)),0).
grandparent(mum(dad(jane)),mum(mum(jo)),0).
grandparent(mum(dad(jane)),peter,0).
grandparent(mum(dad(jane)),dad(peter),0).
grandparent(mum(dad(jane)),mum(peter),0).
grandparent(mum(dad(jane)),dad(dad(peter)),0).
grandparent(mum(dad(jane)),dad(mum(peter)),0).
grandparent(mum(dad(jane)),mum(dad(peter)),0).
grandparent(mum(dad(jane)),mum(mum(peter)),0).
grandparent(mum(dad(jane)),dad(jane),0).
grandparent(mum(dad(jane)),mum(jane),0).
grandparent(mum(dad(jane)),dad(dad(jane)),0).
grandparent(mum(dad(jane)),dad(mum(jane)),0).
grandparent(mum(dad(jane)),mum(dad(jane)),0).
grandparent(mum(dad(jane)),mum(mum(jane)),0).
grandparent(mum(mum(jane)),bob,0).
grandparent(mum(mum(jane)),dad(bob),0).
grandparent(mum(mum(jane)),mum(bob),0).
grandparent(mum(mum(jane)),dad(dad(bob)),0).
grandparent(mum(mum(jane)),dad(mum(bob)),0).
grandparent(mum(mum(jane)),mum(dad(bob)),0).
grandparent(mum(mum(jane)),mum(mum(bob)),0).
grandparent(mum(mum(jane)),jo,0).
grandparent(mum(mum(jane)),dad(jo),0).
grandparent(mum(mum(jane)),mum(jo),0).
grandparent(mum(mum(jane)),dad(dad(jo)),0).
grandparent(mum(mum(jane)),dad(mum(jo)),0).
grandparent(mum(mum(jane)),mum(dad(jo)),0).
grandparent(mum(mum(jane)),mum(mum(jo)),0).
grandparent(mum(mum(jane)),peter,0).
grandparent(mum(mum(jane)),dad(peter),0).
grandparent(mum(mum(jane)),mum(peter),0).
grandparent(mum(mum(jane)),dad(dad(peter)),0).
grandparent(mum(mum(jane)),dad(mum(peter)),0).
grandparent(mum(mum(jane)),mum(dad(peter)),0).
grandparent(mum(mum(jane)),mum(mum(peter)),0).
grandparent(mum(mum(jane)),dad(jane),0).
grandparent(mum(mum(jane)),mum(jane),0).
grandparent(mum(mum(jane)),dad(dad(jane)),0).
grandparent(mum(mum(jane)),dad(mum(jane)),0).
grandparent(mum(mum(jane)),mum(dad(jane)),0).
grandparent(mum(mum(jane)),mum(mum(jane)),0).
grandparent(dad(dad(bob)),bob,1).
grandparent(dad(mum(bob)),bob,1).
grandparent(mum(dad(bob)),bob,1).
grandparent(mum(mum(bob)),bob,1).
grandparent(dad(dad(jo)),jo,1).
grandparent(dad(mum(jo)),jo,1).
grandparent(mum(dad(jo)),jo,1).
grandparent(mum(mum(jo)),jo,1).
grandparent(dad(dad(peter)),peter,1).
grandparent(dad(mum(peter)),peter,1).
grandparent(mum(dad(peter)),peter,1).
grandparent(mum(mum(peter)),peter,1).
grandparent(dad(dad(jane)),jane,1).
grandparent(dad(mum(jane)),jane,1).
grandparent(mum(dad(jane)),jane,1).
grandparent(mum(mum(jane)),jane,1).
