urdmi_cols(col(animal,primary)).
animal(dog).
animal(dolphin).
animal(platypus).
animal(bat).
animal(trout).
animal(herring).
animal(shark).
animal(eel).
animal(lizard).
animal(crocodile).
animal(t_rex).
animal(turtle).
animal(snake).
animal(eagle).
animal(ostrich).
animal(penguin).
animal(cat).
animal(dragon).
animal(girl).
animal(boy).
