class(eagle,bird,1).
class(bat,mammal,1).
class(dog,mammal,1).
class(bat,mammal,1).
class(eagle,bird,1).
class(ostrich,bird,1).
class(shark,fish,1).
class(crocodile,reptile,1).
class(bat,mammal,1).
class(shark,fish,1).
class(penguin,bird,1).
class(shark,fish,1).
class(crocodile,reptile,1).
class(crocodile,reptile,1).
class(shark,fish,1).
class(dog,mammal,1).
class(snake,reptile,1).
class(platypus,mammal,1).
class(t_rex,reptile,1).
class(crocodile,reptile,1).
