urdmi_cols(col(animal,foreign),col(class,foreign),col(group,none)).
class(bat,mammal,1).
class(dog,mammal,1).
class(bat,mammal,1).
class(bat,mammal,1).
class(dog,mammal,1).
class(platypus,mammal,1).
class(eagle,nmammal,1).
class(eagle,nmammal,1).
class(ostrich,nmammal,1).
class(shark,nmammal,1).
class(crocodile,nmammal,1).
class(shark,nmammal,1).
class(penguin,nmammal,1).
class(shark,nmammal,1).
class(crocodile,nmammal,1).
class(crocodile,nmammal,1).
class(shark,nmammal,1).
class(snake,nmammal,1).
class(t_rex,nmammal,1).
class(crocodile,nmammal,1).
